'use client';

import { useEffect, useMemo, useState } from 'react';

const levelTitles = [
  'What is Securitization?','SPV Mechanics & True Sale','Tranches, Ratings & Pay Rules','Waterfalls & Triggers','Collateral Performance','Build a Mini Waterfall','Read a Presale','Pricing, Spreads, WAL & Yield','Surveillance & KPIs','Presale-to-Price Capstone','Prime vs Subprime','Scenario & Sensitivity Lab','Legal Documents','Advanced Waterfalls','Counterparties & Hedging','Static Pools & Roll Rates','Data Tape & Stratification','Investor Memo & Credit Pitch','Regulation & Risk Retention','Macro Drivers','Servicing & Recoveries','Deal Lifecycle','Relative Value & Comps','ESG, EVs & Future Trends','Secondary Trading & Downgrades','Grand Capstone','Ratings & CE Backsolve','Structuring Lab','Excel Model','Final Exam','Funding & Pool Management','Multi-Multi Encumbrance'
];

const lessonSections = [
  { id:'mission', label:'Mission', title:'What securitization does' },
  { id:'why', label:'Why it exists', title:'Why originators use it' },
  { id:'players', label:'Players', title:'Meet the deal team' },
  { id:'protection', label:'Protection', title:'How the structure absorbs risk' },
  { id:'example', label:'Example', title:'A tiny $100 million deal' },
];

const cards = [
  { front:'Securitization', back:'Turning a pool of contractual cash flows, such as auto loans, into securities that investors can buy.' },
  { front:'SPV / Issuer', back:'A separate, limited-purpose entity that owns the loans and issues the notes.' },
  { front:'Waterfall', back:'The contractual priority that determines who gets paid first from available collections.' },
  { front:'Credit enhancement', back:'Protection for noteholders through subordination, overcollateralization, excess spread, or reserves.' },
  { front:'Sequential amortization', back:'Principal pays the senior notes first, reducing their outstanding balance and risk before junior notes.' },
];

const quiz = [
  { q:'What is the primary role of the SPV?', options:['Originate new auto loans','Hold the loan pool and issue notes','Set borrower interest rates','Guarantee every investor payment'], answer:1, explain:'The SPV owns the transferred assets and issues the securities; its separation helps make the structure bankruptcy-remote.' },
  { q:'Which order best describes the basic transaction?', options:['Investors → borrowers → SPV','Borrowers → servicer/SPV → investors','SPV → borrowers → originator','Rating agency → SPV → borrowers'], answer:1, explain:'Borrowers make payments, the servicer collects them for the SPV, and the waterfall distributes available cash to investors.' },
  { q:'Who benefits most from sequential amortization during stress?', options:['Senior noteholders','The residual holder','New borrowers','The vehicle dealer'], answer:0, explain:'Senior notes receive principal first, shrinking their exposure before more junior claims are paid.' },
  { q:'Which item is NOT a common form of credit enhancement?', options:['Subordination','Overcollateralization','Excess spread','A higher borrower mileage'], answer:3, explain:'Mileage may affect collateral risk, but it is not structural credit enhancement.' },
  { q:'What usually happens after a performance trigger fails?', options:['All debt is forgiven','Cash may be trapped or redirected to seniors','The SPV originates more loans','Junior investors are paid first'], answer:1, explain:'Triggers protect senior investors by restricting junior distributions and redirecting cash to build protection or pay seniors faster.' },
];

type DemoSection = { label:string; title:string; kicker:string; lead:string; bullets:Array<{title:string;text:string}>; callout:string };
type DemoDay = { title:string; shortTitle:string; prerequisite:string; later:string; sections:DemoSection[]; cards:{front:string;back:string}[]; quiz:typeof quiz };

const demoDays:Record<number,DemoDay> = {
  2:{title:'SPV Mechanics, True Sale & Bankruptcy Remoteness',shortTitle:'Why the deal needs a legal home',prerequisite:'Day 1 · Complete deal flow',later:'Day 13 · Legal documents',sections:[
    {label:'Purpose',title:'Why create an SPV?',kicker:'NEW PLAYER: a legal box with one job.',lead:'The SPV separates the loan pool from the originator and becomes the financing vehicle that issues notes to investors.',bullets:[{title:'Risk isolation',text:'The loans should remain outside the originator’s bankruptcy estate.'},{title:'Financing vehicle',text:'The SPV issues notes under a defined set of documents and payment rules.'},{title:'Investor simplicity',text:'Covenants, reporting, accounts, and cash movements become standardized.'}],callout:'Product Manager lens: the SPV creates a clean system boundary with restricted responsibilities.'},
    {label:'Remoteness',title:'Bankruptcy-remote does not mean bankruptcy-proof',kicker:'DEFENCE MODE: separate, restrict, evidence.',lead:'Bankruptcy remoteness is built through several reinforcing legal and operational controls.',bullets:[{title:'Limited purpose',text:'The charter restricts the SPV to holding assets, issuing notes, and related actions.'},{title:'Separateness',text:'Separate books, accounts, records, and arm’s-length dealings reduce consolidation risk.'},{title:'Independent control',text:'Material actions may require an independent director or manager.'},{title:'Non-petition',text:'Transaction parties agree not to force the SPV into bankruptcy for a defined period.'}],callout:'No single clause creates remoteness; the protections work as a system.'},
    {label:'True sale',title:'A sale in substance—not a disguised loan',kicker:'TRANSFER CHECK: who really controls the assets?',lead:'The transfer should move the benefits, burdens, and control of the receivables to the SPV for fair consideration.',bullets:[{title:'Limited recourse',text:'The originator should not bear ordinary credit losses after the transfer.'},{title:'Fair consideration',text:'The purchase price and terms should look arm’s length.'},{title:'Narrow repurchases',text:'Repurchases are generally for breached representations or ineligible assets—not poor credit performance.'},{title:'Legal opinions',text:'True-sale and non-consolidation opinions support the intended treatment.'}],callout:'If the originator must repurchase every defaulted loan, the “sale” starts looking like secured borrowing.'},
    {label:'Cash risks',title:'Keep collections away from servicer failure',kicker:'CASH CONTROL: shorten the time money can get stuck.',lead:'Borrower collections must move into controlled trust accounts quickly and predictably.',bullets:[{title:'Commingling risk',text:'Cash held by a failed servicer may become trapped in its estate.'},{title:'Daily sweeps',text:'Frequent transfers reduce the amount and time exposed to the servicer.'},{title:'Lockbox',text:'Blocked or springing accounts tighten control, especially after a downgrade.'},{title:'Setoff risk',text:'Eligibility rules, assignment notices, and diversification limit borrower offsets.'}],callout:'Meeting decoder: “springing lockbox at BBB-” means cash control tightens immediately after a downgrade.'}
  ],cards:[{front:'Bankruptcy remoteness',back:'A package of legal and operational features designed to isolate the SPV and its assets from an originator bankruptcy.'},{front:'True sale',back:'A transfer that moves control, benefits, and burdens to the buyer rather than functioning as a secured loan.'},{front:'Non-consolidation opinion',back:'Legal support that the SPV should not be combined with the originator in bankruptcy.'},{front:'Commingling risk',back:'The risk that borrower cash held by a servicer becomes trapped if that servicer fails.'},{front:'Springing lockbox',back:'A cash-control mechanism that activates after a defined event such as a servicer downgrade.'}],quiz:[
    {q:'What is the central purpose of the SPV?',options:['Originate loans','Legally isolate assets and issue notes','Guarantee all losses','Set vehicle prices'],answer:1,explain:'The SPV holds transferred assets and issues notes while helping isolate the pool from the originator.'},
    {q:'Which feature supports bankruptcy remoteness?',options:['Shared accounts with the sponsor','Unlimited activities','Separateness covenants','Mandatory credit-loss repurchases'],answer:2,explain:'Separate books, accounts, and dealings reinforce that the SPV is distinct.'},
    {q:'What could make a sale look like secured borrowing?',options:['Fair consideration','Broad recourse for credit losses','A true-sale opinion','A collateral schedule'],answer:1,explain:'Broad recourse leaves ordinary asset risk with the seller and weakens sale treatment.'},
    {q:'Why do daily sweeps reduce commingling risk?',options:['They increase coupons','They shorten cash exposure to the servicer','They eliminate defaults','They replace the trustee'],answer:1,explain:'Less cash remains with the servicer for less time.'},
    {q:'What repurchase is typically permitted?',options:['Every defaulted asset','Any loan with a lower score','A loan breaching a representation','Any prepaid loan'],answer:2,explain:'Repurchases usually cure breached representations or ineligible assets, not ordinary credit losses.'}
  ]},
  3:{title:'Tranches, Ratings, Subordination & Pay Rules',shortTitle:'Split risk into layers',prerequisite:'Days 1–2 · Flow and SPV',later:'Day 14 · Advanced waterfalls',sections:[
    {label:'Tranches',title:'One pool, different risk-and-return slices',kicker:'CHOOSE YOUR LEVEL: senior, mezzanine, or residual.',lead:'Tranching directs cash and losses differently across classes so investors can choose the profile that fits them.',bullets:[{title:'Class A',text:'Paid first, protected by everything below it, and typically lowest yielding.'},{title:'Mezzanine',text:'Takes losses after the residual but before senior notes and earns more yield.'},{title:'Residual',text:'Paid last and absorbs the first dollar of collateral loss.'}],callout:'A AAA bond does not mean every underlying auto loan is AAA; structure creates protection.'},
    {label:'Protection',title:'Subordination creates the loss ladder',kicker:'SHIELD STACK: losses climb from the bottom.',lead:'Senior protection combines subordination with overcollateralization, excess spread, reserves, and cash-trapping triggers.',bullets:[{title:'Subordination',text:'Junior claims absorb losses before seniors.'},{title:'OC',text:'Collateral exceeds rated notes, creating an asset cushion.'},{title:'Excess spread',text:'Asset income remaining after fees and bond interest can absorb losses or build protection.'},{title:'Reserve',text:'Cash funded at closing covers defined shortfalls.'}],callout:'Available credit enhancement must remain meaningful under the relevant rating stress.'},
    {label:'Ratings',title:'Ratings connect stress to available protection',kicker:'STRESS TEST: can the class survive the target scenario?',lead:'Agencies assess collateral losses, structural protection, operations, and legal risks at progressively tougher stress levels.',bullets:[{title:'Collateral',text:'Expected defaults, severity, recoveries, and timing drive stressed loss vectors.'},{title:'Structure',text:'Available CE and payment rules determine whether promised payments survive.'},{title:'Operations',text:'Servicing, data, representations, and counterparties can constrain ratings.'}],callout:'Simplified rule: available CE under the target stress must meet or exceed required CE.'},
    {label:'Pay rules',title:'Sequential versus pro-rata principal',kicker:'PAY MODE: safety first or proportional sharing?',lead:'Sequential pay sends principal to the most senior class first; pro-rata shares it while performance remains strong.',bullets:[{title:'Sequential',text:'Pays Class A down first, reduces senior exposure, and tends to build OC.'},{title:'Pro-rata',text:'Shares principal by balance and is usually conditional on passing triggers.'},{title:'Flip triggers',text:'Weak performance or a step-up date can switch the deal permanently to sequential.'}],callout:'In stress, sequential pay usually benefits senior investors most.'}
  ],cards:[{front:'Tranche',back:'A class of securities with its own priority, risk, maturity, and return.'},{front:'Subordination',back:'Protection created when junior claims absorb losses before more senior claims.'},{front:'Sequential pay',back:'All principal pays the senior class first, then moves down the capital structure.'},{front:'Pro-rata pay',back:'Principal is shared across classes in proportion to balances while required tests pass.'},{front:'Rating stress',back:'A scenario used to test whether available enhancement can support payments at a target rating.'}],quiz:[
    {q:'Who takes the first dollar of loss?',options:['Class A','Trustee','Residual/equity','Borrowers collectively'],answer:2,explain:'The residual is the first-loss position and protects rated notes above it.'},
    {q:'Which pay rule most protects seniors in stress?',options:['Pro-rata','Sequential','Random allocation','Residual-first principal'],answer:1,explain:'Sequential pay reduces senior balance and exposure fastest.'},
    {q:'How can OC increase?',options:['Pay notes faster than assets decline','Increase fees','Pay equity first','Remove triggers'],answer:0,explain:'Sequential amortization and trapped excess spread can reduce notes faster than collateral.'},
    {q:'What do triggers do after a breach?',options:['Increase residual payments','Redirect cash toward senior protection','Cancel the notes','Raise borrower APRs'],answer:1,explain:'Triggers can trap cash, turbo seniors, or flip the deal to sequential pay.'},
    {q:'What supports a target rating?',options:['Issuer preference alone','CE surviving the target stress','Only loan count','Only bond coupon'],answer:1,explain:'The class must have enough structural and operational protection under the target stress.'}
  ]},
  4:{title:'Waterfall & Triggers Deep Dive',shortTitle:'Follow every dollar',prerequisite:'Day 3 · Tranches and pay rules',later:'Day 6 · Build a mini waterfall',sections:[
    {label:'Cycle',title:'The monthly payment-date cycle',kicker:'GAME LOOP: collect, calculate, test, pay.',lead:'Each payment date follows a repeatable operational sequence from borrower collections to investor distributions.',bullets:[{title:'Collection period',text:'Borrower interest, principal, and recoveries accumulate.'},{title:'Determination date',text:'The parties calculate amounts due, fees, and trigger results.'},{title:'Payment date',text:'The trustee applies available funds through the contractual waterfall.'}],callout:'The cut-off date defines which receivables belong to the transferred pool.'},
    {label:'Waterfall',title:'Priority of payments is the deal’s operating code',kicker:'QUEUE RULES: every dollar waits its turn.',lead:'A simplified sequential waterfall pays senior operating costs and noteholders before reserves and the residual.',bullets:[{title:'1 · Senior fees',text:'Trustee, administration, servicing, and permitted hedge costs.'},{title:'2 · Class A',text:'Senior interest and then targeted or sequential principal.'},{title:'3 · Class B',text:'Mezzanine interest and principal after required senior payments.'},{title:'4 · Protection',text:'Replenish reserves and build or maintain required OC.'},{title:'5 · Residual',text:'Release remaining cash only when all conditions permit.'}],callout:'Reserve top-up comes before equity. Documents—not intuition—control the exact order.'},
    {label:'Tests',title:'Triggers convert performance into cash actions',kicker:'SYSTEM CHECK: pass, cure, or redirect.',lead:'OC, IC, delinquency, and cumulative-net-loss tests continuously check whether protection is adequate.',bullets:[{title:'OC ratio',text:'Adjusted collateral divided by outstanding rated notes.'},{title:'IC ratio',text:'Interest collections divided by senior fees and note interest due.'},{title:'Delinquency',text:'A threshold catches deterioration before final losses arrive.'},{title:'CNL',text:'Cumulative net losses are compared with a seasoning-based curve.'}],callout:'A test is valuable because it changes what cash is allowed to do.'},
    {label:'Breach',title:'When OC fails, trap and turbo',kicker:'BOSS EVENT: 1.08x versus a 1.10x requirement.',lead:'Assume $650k interest, $30k recoveries, $510k of fees and note interest, and $2.1mm of principal.',bullets:[{title:'Excess spread',text:'$650k + $30k - $510k = $170k before principal.'},{title:'Trap',text:'The $170k is retained for reserve or OC instead of going to equity.'},{title:'Turbo',text:'The $2.1mm of principal pays senior notes first to accelerate the cure.'},{title:'Flip',text:'A pro-rata structure may switch to sequential pay.'}],callout:'Meeting decoder: “trap and turbo until OC >= 110%” means residual off and seniors pay down faster.'}
  ],cards:[{front:'Waterfall',back:'The contractual order in which available collections are distributed.'},{front:'OC ratio',back:'Adjusted collateral balance divided by outstanding rated notes.'},{front:'IC ratio',back:'Interest collections divided by note interest and senior fees due.'},{front:'Turbo',back:'Redirecting available cash to accelerate senior principal repayment.'},{front:'PDL',back:'A ledger tracking principal used to cover interest, which must generally be cured before junior paydowns.'}],quiz:[
    {q:'What does an OC failure usually do to equity?',options:['Increases it','Stops or traps distributions','Guarantees it','Pays it before fees'],answer:1,explain:'Residual cash is commonly trapped until protection is restored.'},
    {q:'Which item is paid first in a typical waterfall?',options:['Equity','Reserve release','Senior fees','Class B principal'],answer:2,explain:'Trustee, servicing, and other senior expenses generally come first.'},
    {q:'What can force pro-rata pay to become sequential?',options:['A trigger breach','A new vehicle sale','A higher residual payment','A borrower address change'],answer:0,explain:'OC, IC, delinquency, or CNL breaches commonly cause the flip.'},
    {q:'What is excess spread in the example?',options:['$120k','$170k','$510k','$2.1mm'],answer:1,explain:'$650k interest + $30k recoveries - $510k costs and note interest = $170k.'},
    {q:'Why does a PDL matter?',options:['It tracks principal used for interest','It sets borrower APR','It selects vehicles','It replaces the trustee'],answer:0,explain:'The ledger preserves the claim of principal and is generally cured before junior distributions.'}
  ]}
};

const mapNodes = [
  { day:1, name:'Core idea', detail:'See the complete borrower-to-investor flow.', state:'current' },
  { day:2, name:'The SPV', detail:'Learn why the issuer is legally separate.', state:'next' },
  { day:3, name:'Tranches', detail:'Split the deal into different risk and return profiles.', state:'future' },
  { day:4, name:'Waterfall', detail:'Follow each dollar through the priority of payments.', state:'future' },
  { day:6, name:'Build it', detail:'Apply the foundation in a mini waterfall.', state:'milestone' },
];

const phases = [
  { name:'Build the foundation', days:'1–7', tone:'foundation', concepts:'Flow · SPV · Tranches · Waterfalls · Credit' },
  { name:'Analyze a deal', days:'8–12', tone:'analyze', concepts:'Pricing · Surveillance · Scenarios' },
  { name:'Open the machine', days:'13–18', tone:'machine', concepts:'Documents · Data · Advanced structure' },
  { name:'See the whole market', days:'19–25', tone:'market', concepts:'Regulation · Macro · Trading' },
  { name:'Demonstrate mastery', days:'26–30', tone:'mastery', concepts:'Capstone · Ratings · Model · Exam' },
  { name:'Advanced bonus levels', days:'31–32', tone:'bonus', concepts:'Funding · Pool controls · Encumbrance' },
];

const tourSteps = [
  { target:'[data-tour="topics"]', eyebrow:'WELCOME TO STUDY ARCADE', title:'Choose a topic, then enter its learning journey', text:'Study Arcade is the learning platform. Securitization Fundamentals is the current topic; the Topic Library is where additional organizational subjects will live.' },
  { target:'[data-tour="brand"]', eyebrow:'CURRENT TOPIC', title:'Securitization Fundamentals', text:'This topic is a 30-day core journey with two advanced bonus levels, using auto loans as the practical case study for understanding securitization.' },
  { target:'[data-tour="journey"]', eyebrow:'THE ROADMAP', title:'Always know where you are', text:'The Journey panel keeps all 32 levels visible, marks your current position, and lets you preview what comes next.' },
  { target:'[data-tour="learning-map"]', eyebrow:'THE MENTAL MODEL', title:'See phases and prerequisites together', text:'The Learning Map is both the course index and the conceptual map. It shows which earlier ideas unlock advanced lessons.' },
  { target:'[data-tour="lesson"]', eyebrow:'DAILY MISSION', title:'Learn in small, connected sections', text:'Every day moves from plain-English intuition into mechanics, examples, and application without losing the bigger picture.' },
  { target:'[data-tour="context"]', eyebrow:'LEARNING CONTEXT', title:'Understand what today builds on and unlocks', text:'The Previously → Today → Later thread explains what a lesson depends on and where the learner will apply it next.' },
  { target:'[data-tour="practice"]', eyebrow:'ACTIVE RECALL', title:'Practise instead of only reading', text:'The Practice Studio combines concept connections, flashcards, and quizzes with immediate feedback.' },
  { target:'[data-tour="tool-body"]', eyebrow:'FLASHCARDS', title:'Turn concepts into recall', text:'Flip each card, judge whether you know it, and build a review deck around concepts that need more practice.', tool:'cards' as StudioTool },
  { target:'[data-tour="tool-body"]', eyebrow:'KNOWLEDGE CHECK', title:'Prove and improve understanding', text:'The quiz explains every answer and uses an 80% target for mastery—not just completion.', tool:'quiz' as StudioTool },
  { target:'[data-tour="progress"]', eyebrow:'YOUR PROGRESS', title:'Pick up where you left off', text:'Sections, mastered cards, quiz results, XP, and progress are saved on this device. You are ready to start Day 1.' },
  { target:'[data-tour="present"]', eyebrow:'RETAIN THE TRAINING', title:'Return to the slides used in the session', text:'Present Day 1 gives trainers a ready teaching view and remains available to the new employee afterward, preserving the explanations and sequence of the original training.' },
];

type StudioTool = 'map'|'cards'|'quiz';

export default function Home(){
  const [selectedDay,setSelectedDay]=useState(1);
  const [section,setSection]=useState(0);
  const [completed,setCompleted]=useState<string[]>([]);
  const [tool,setTool]=useState<StudioTool>('map');
  const [expanded,setExpanded]=useState(false);
  const [notice,setNotice]=useState('');
  const [mapNode,setMapNode]=useState(0);
  const [cardIndex,setCardIndex]=useState(0);
  const [flipped,setFlipped]=useState(false);
  const [mastered,setMastered]=useState<number[]>([]);
  const [answers,setAnswers]=useState<Record<number,number>>({});
  const [submitted,setSubmitted]=useState(false);
  const [tourStep,setTourStep]=useState(-1);
  const [presenting,setPresenting]=useState(false);
  const [demoCompleted,setDemoCompleted]=useState<Record<number,number[]>>({});
  const [demoMastered,setDemoMastered]=useState<Record<number,number[]>>({});
  const [demoAnswers,setDemoAnswers]=useState<Record<number,Record<number,number>>>({});
  const [demoSubmitted,setDemoSubmitted]=useState<number[]>([]);
  const [mapOpen,setMapOpen]=useState(false);
  const [topicOpen,setTopicOpen]=useState(false);

  useEffect(()=>{
    try {
      const saved=localStorage.getItem('sa-day1-progress');
      if(saved){const data=JSON.parse(saved);setCompleted(data.completed||[]);setMastered(data.mastered||[]);setAnswers(data.answers||{});setSubmitted(!!data.submitted);}
    } catch {}
  },[]);
  useEffect(()=>{
    const params=new URLSearchParams(window.location.search);
    if(params.get('tour')==='1'){
      setTourStep(0);
      window.history.replaceState({},'',`${window.location.pathname}${window.location.hash}`);
    }
  },[]);
  useEffect(()=>{
    localStorage.setItem('sa-day1-progress',JSON.stringify({completed,mastered,answers,submitted}));
  },[completed,mastered,answers,submitted]);
  useEffect(()=>{try{const saved=localStorage.getItem('sa-demo-progress');if(saved){const d=JSON.parse(saved);setDemoCompleted(d.completed||{});setDemoMastered(d.mastered||{});setDemoAnswers(d.answers||{});setDemoSubmitted(d.submitted||[])}}catch{}},[]);
  useEffect(()=>{localStorage.setItem('sa-demo-progress',JSON.stringify({completed:demoCompleted,mastered:demoMastered,answers:demoAnswers,submitted:demoSubmitted}))},[demoCompleted,demoMastered,demoAnswers,demoSubmitted]);
  useEffect(()=>{
    if(tourStep>=0){const requested=tourSteps[tourStep]?.tool;if(requested)setTool(requested);}
  },[tourStep]);

  const activeQuiz=selectedDay===1?quiz:demoDays[selectedDay].quiz;
  const activeCards=selectedDay===1?cards:demoDays[selectedDay].cards;
  const activeAnswers=selectedDay===1?answers:(demoAnswers[selectedDay]||{});
  const activeMastered=selectedDay===1?mastered:(demoMastered[selectedDay]||[]);
  const activeSubmitted=selectedDay===1?submitted:demoSubmitted.includes(selectedDay);
  const activeCompleted=selectedDay===1?completed.length:(demoCompleted[selectedDay]||[]).length;
  const requiredSections=selectedDay===1?5:4;
  const score=useMemo(()=>activeQuiz.reduce((sum,item,i)=>sum+(activeAnswers[i]===item.answer?1:0),0),[activeAnswers,activeQuiz]);
  const xp=activeCompleted*20+activeMastered.length*5+(activeSubmitted?score*10:0);
  const progress=Math.round(((activeCompleted/requiredSections+activeMastered.length/5+(activeSubmitted?1:0))/3)*100);

  function finishSection(){
    if(selectedDay>1){const done=demoCompleted[selectedDay]||[];if(!done.includes(section))setDemoCompleted({...demoCompleted,[selectedDay]:[...done,section]});if(section<3)setSection(section+1);else{setTool('quiz');setNotice(`Day ${selectedDay} lesson complete — finish the quiz to clear the level.`)}return;}
    const id=lessonSections[section].id;
    if(!completed.includes(id))setCompleted([...completed,id]);
    if(section<lessonSections.length-1)setSection(section+1);else{setTool('quiz');setNotice('Lesson complete — your final mission is the quiz!');}
  }
  function chooseLevel(index:number){
    if(index<=3){setSelectedDay(index+1);setSection(0);setCardIndex(0);setFlipped(false);setTool('map');setNotice(`Day ${index+1}: ${levelTitles[index]}`);return;}
    setNotice(`Day ${index+1} is on the roadmap. We’re polishing Day 1 first.`);
  }
  function resetDay(){
    if(!confirm(`Reset all Day ${selectedDay} progress on this device?`))return;
    if(selectedDay>1){const nextCompleted={...demoCompleted};delete nextCompleted[selectedDay];const nextMastered={...demoMastered};delete nextMastered[selectedDay];const nextAnswers={...demoAnswers};delete nextAnswers[selectedDay];setDemoCompleted(nextCompleted);setDemoMastered(nextMastered);setDemoAnswers(nextAnswers);setDemoSubmitted(demoSubmitted.filter(d=>d!==selectedDay));setSection(0);setCardIndex(0);setFlipped(false);setNotice(`Day ${selectedDay} progress reset.`);return;}
    setCompleted([]);setMastered([]);setAnswers({});setSubmitted(false);setSection(0);setCardIndex(0);setFlipped(false);setNotice('Day 1 progress reset.');
  }

  return <main className="app-shell">
    <header className="topbar">
      <div className="brand-mark" data-tour="brand">SA</div><div className="brand-copy"><strong>Study Arcade</strong><button className="topic-switcher" data-tour="topics" onClick={()=>setTopicOpen(true)}><small>CURRENT TOPIC</small><b>Securitization Fundamentals</b><span>⌄</span></button></div>
      <div className="header-progress" data-tour="progress" aria-label={`${progress}% complete`}><span>DAY {selectedDay} · {progress}% COMPLETE</span><div><i style={{width:`${Math.max(progress,3)}%`}} /></div></div>
      <button className="tour-button" onClick={()=>setTourStep(0)}>✦ Take a tour</button><button className="present-secondary" data-tour="present" onClick={()=>setPresenting(true)}>▶ Present Day {selectedDay}</button><button className="icon-button" onClick={resetDay} aria-label="Reset Day 1 progress" title="Reset progress">↺</button><div className="avatar">PM</div>
    </header>

    {notice&&<button className="toast" onClick={()=>setNotice('')} aria-label="Dismiss message">{notice}<span>×</span></button>}

    <section className="workspace">
      <aside className="panel journey-panel" data-tour="journey">
        <div className="panel-heading"><div><span className="eyebrow">YOUR JOURNEY</span><h2>32 learning levels</h2></div><span className="journey-score">{progress}%</span></div>
        <button className="learning-map-entry" data-tour="learning-map" onClick={()=>setMapOpen(true)}><span>◇</span><p><b>Learning Map</b>All phases, concepts & prerequisites</p><i>↗</i></button>
        <div className="phase-card"><span>PHASE 1 OF 5 · CURRENT</span><strong>Build the foundation</strong><div className="phase-meter"><i style={{width:`${Math.max(progress/7,2)}%`}} /></div><small>Day {selectedDay} of 7 · Flow, structure, credit and waterfalls</small></div>
        <nav className="level-list" aria-label="Course levels">{levelTitles.slice(0,expanded?32:8).map((title,index)=><button onClick={()=>chooseLevel(index)} className={index===selectedDay-1?'level active':'level'} key={title}><span className="level-number">{index===selectedDay-1?'▶':index+1}</span><span><b>{index<30?`Day ${index+1}`:`Bonus ${index-29}`}</b>{title}</span>{index===selectedDay-1?<em>NOW</em>:<span className="roadmap-dot">○</span>}</button>)}</nav>
        <button className="all-levels" onClick={()=>setExpanded(!expanded)}>{expanded?'Show core levels':'View all 32 levels'} <span>{expanded?'↑':'→'}</span></button>
        <div className="bonus-note"><span>★</span><p><b>2 bonus levels await</b>Advanced funding and controls unlock after graduation.</p></div>
      </aside>

      <article className="panel lesson-panel" data-tour="lesson">
        <div className="lesson-toolbar"><span className="level-pill">LEVEL {String(selectedDay).padStart(2,'0')} · FOUNDATION</span><div className="section-tabs" role="tablist">{(selectedDay===1?lessonSections:demoDays[selectedDay].sections).map((item:any,i:number)=><button key={item.id||item.label} className={i===section?'current':(selectedDay===1?completed.includes(item.id):(demoCompleted[selectedDay]||[]).includes(i))?'done':''} onClick={()=>setSection(i)} aria-label={`Open ${item.label}`}>{(selectedDay===1?completed.includes(item.id):(demoCompleted[selectedDay]||[]).includes(i))?'✓ ':''}{i+1}</button>)}</div><span>⏱ 45–60 min</span></div>
        <div className="lesson-scroll" key={lessonSections[section].id}>
          {selectedDay===1?<>{section===0&&<MissionSection/>}{section===1&&<WhySection/>}{section===2&&<PlayersSection/>}{section===3&&<ProtectionSection/>}{section===4&&<ExampleSection/>}</>:<DemoLesson day={selectedDay} section={section}/>} 
        </div>
        <footer className="lesson-footer"><div><span>DAY {selectedDay} PROGRESS · {activeCompleted}/{requiredSections} SECTIONS</span><div className="footer-meter"><i style={{width:`${activeCompleted/requiredSections*100}%`}} /></div></div><button onClick={finishSection}>{section===requiredSections-1?'Finish lesson':'Complete & continue'} <span>→</span></button></footer>
      </article>

      <aside className="panel studio-panel" data-tour="practice">
        <div className="panel-heading"><div><span className="eyebrow">PRACTICE STUDIO</span><h2>Learn by doing</h2></div><span className="xp">{xp} XP</span></div>
        <div className="studio-callout"><span>✨</span><p><b>Your Day {selectedDay} toolkit</b>Map the idea, practise recall, then prove it.</p></div>
        <div className="studio-tabs" role="tablist">
          <button onClick={()=>setTool('map')} className={tool==='map'?'active':''}>◇ Map</button>
          <button onClick={()=>setTool('cards')} className={tool==='cards'?'active':''}>▣ Cards</button>
          <button onClick={()=>setTool('quiz')} className={tool==='quiz'?'active':''}>? Quiz</button>
        </div>
        <div data-tour="tool-body">{tool==='map'&&<MapTool day={selectedDay} selected={mapNode} setSelected={setMapNode} openFullMap={()=>setMapOpen(true)}/>} 
        {tool==='cards'&&<CardTool data={activeCards} index={cardIndex} setIndex={setCardIndex} flipped={flipped} setFlipped={setFlipped} mastered={activeMastered} setMastered={(next)=>selectedDay===1?setMastered(next):setDemoMastered({...demoMastered,[selectedDay]:next})}/>} 
        {tool==='quiz'&&<QuizTool data={activeQuiz} answers={activeAnswers} setAnswers={(next)=>selectedDay===1?setAnswers(next):setDemoAnswers({...demoAnswers,[selectedDay]:next})} submitted={activeSubmitted} setSubmitted={(next)=>selectedDay===1?setSubmitted(next):setDemoSubmitted(next?[...new Set([...demoSubmitted,selectedDay])]:demoSubmitted.filter(d=>d!==selectedDay))} score={score}/>}</div>
        <div className="streak"><span>{progress===100?'🏆':'🔥'}</span><p><b>{progress===100?`Day ${selectedDay} mastered`:'Build your streak'}</b>{progress===100?'You cleared this level.':'Complete the lesson and quiz to light it up.'}</p><strong>{progress===100?`${xp} XP`:`Day ${selectedDay}`}</strong></div>
      </aside>
    </section>

    <div className="mobile-tools" aria-label="Practice tools"><button onClick={()=>{setTool('map');setNotice('Open on desktop to use the full Practice Studio.')}}>◇ Map</button><button onClick={()=>{setTool('cards');setNotice('Open on desktop to use flashcards.')}}>▣ Cards</button><button onClick={()=>{setTool('quiz');setNotice('Open on desktop to take the quiz.')}}>? Quiz</button></div>

    {mapOpen&&<LearningMap close={()=>setMapOpen(false)} chooseDay={(day)=>{setMapOpen(false);chooseLevel(day-1)}}/>}
    {topicOpen&&<TopicLibrary close={()=>setTopicOpen(false)}/>}
    {tourStep>=0&&<GuidedTour step={tourStep} setStep={setTourStep}/>} 
    {presenting&&<Presentation day={selectedDay} section={section} setSection={setSection} close={()=>setPresenting(false)}/>} 
  </main>;
}

function MissionSection(){return <><div className="lesson-hero"><div className="pixel-art"><span>●</span><span>→</span><span>▰</span><span>→</span><span>▱</span></div><p className="comic-kicker">INSERT COIN: one auto loan, many investors.</p><h1>What is Securitization?</h1><p>Follow a pool of auto loans as it becomes a stack of tradable bonds—and meet every player along the way.</p></div><LearningThread/><section className="content-section"><span className="section-label">MISSION BRIEFING</span><h2>Turn thousands of loans into investable bonds</h2><p>Securitization gathers many small contractual cash flows—like monthly auto-loan payments—and finances them by issuing securities to investors.</p><div className="flow-card"><div><span>🚗</span><b>Borrowers</b><small>make payments</small></div><i>→</i><div><span>🏦</span><b>Originator</b><small>pools loans</small></div><i>→</i><div className="highlight"><span>📦</span><b>SPV / Trust</b><small>issues notes</small></div><i>→</i><div><span>📊</span><b>Investors</b><small>fund the deal</small></div></div><div className="plain-english"><b>💬 In plain English</b><p>The lender turns future borrower payments into funding today. Investors receive those payments according to a strict queue called the waterfall.</p></div></section></>}
function LearningThread(){return <div className="learning-thread" data-tour="context"><div><span>PREVIOUSLY</span><b>Your finance intuition</b></div><i>→</i><div className="today"><span>TODAY</span><b>See the complete deal flow</b></div><i>→</i><div><span>LATER</span><b>Build an actual waterfall</b></div></div>}
function WhySection(){return <section className="deep-section"><span className="section-label">WHY IT EXISTS</span><p className="comic-kicker">POWER-UP: funding today from payments tomorrow.</p><h1>Why would a lender securitize?</h1><p className="lead">The transaction is a funding and risk-management tool—not financial magic. It changes how loans are financed and who bears different slices of risk.</p><div className="learning-grid"><InfoCard icon="↻" title="Recycle capital" text="Convert a pool of loans into cash that can fund new lending."/><InfoCard icon="$" title="Lower funding cost" text="Highly protected senior bonds may price more cheaply than unsecured borrowing."/><InfoCard icon="⇄" title="Transfer risk" text="Junior notes, overcollateralization, and the residual absorb losses before seniors."/><InfoCard icon="≋" title="Match cash flows" text="Finance long-lived assets with liabilities designed around their expected collections."/></div><div className="challenge"><b>Quick thought experiment</b><p>If a lender must wait five years for every borrower to repay, how many new loans can it make today? Securitization helps turn that future cash into current funding.</p></div></section>}
function PlayersSection(){const players=[['Originator / Sponsor','Makes the loans, selects the pool, and sells it to the SPV.'],['SPV / Issuer','Holds the loans and issues the securities.'],['Servicer','Collects borrower payments and manages delinquent accounts.'],['Trustee / Paying Agent','Applies the documents, runs the waterfall, and pays investors.'],['Investors','Choose tranches based on risk, return, and maturity.'],['Rating Agencies','Analyze credit protection under stress assumptions.']];return <section className="deep-section"><span className="section-label">MEET THE DEAL TEAM</span><p className="comic-kicker">MULTIPLAYER MODE: everyone has a different job.</p><h1>Who makes the machine run?</h1><p className="lead">The structure works because responsibilities are separated. Click through these roles mentally from borrower payment to investor receipt.</p><div className="player-list">{players.map(([name,text],i)=><div key={name}><span>{i+1}</span><p><b>{name}</b>{text}</p></div>)}</div><div className="plain-english"><b>🎯 Product Manager lens</b><p>Think of the transaction as a service blueprint: each party owns a step, produces evidence, and creates an operational dependency.</p></div></section>}
function ProtectionSection(){return <section className="deep-section"><span className="section-label">CREDIT ENHANCEMENT</span><p className="comic-kicker">SHIELD UP: losses need somewhere to land.</p><h1>How are senior investors protected?</h1><p className="lead">Credit enhancement creates cushions between collateral losses and promised payments to the rated notes.</p><div className="shield-stack"><div className="senior"><b>Class A · Senior</b><span>Paid first · losses last</span></div><div className="mezz"><b>Class B · Mezzanine</b><span>More yield · more risk</span></div><div className="equity"><b>Residual / OC</b><span>Paid last · losses first</span></div></div><div className="learning-grid compact"><InfoCard icon="↓" title="Subordination" text="Junior claims absorb losses before senior claims."/><InfoCard icon="+" title="Overcollateralization" text="The asset balance exceeds rated note balances."/><InfoCard icon="%" title="Excess spread" text="Asset yield left after fees and bond interest creates a recurring cushion."/><InfoCard icon="▣" title="Reserve" text="Cash is set aside to cover shortfalls when collections are weak."/></div></section>}
function ExampleSection(){return <section className="deep-section"><span className="section-label">WORKED EXAMPLE</span><p className="comic-kicker">BOSS ROUND: follow the money.</p><h1>A tiny $100 million Auto ABS deal</h1><p className="lead">The asset pool earns 8%, while the transaction funds itself with senior and mezzanine notes plus a $10 million residual cushion.</p><div className="deal-grid"><div><span>COLLATERAL</span><b>$100mm</b><small>Auto loans · 8% WA APR</small></div><div><span>CLASS A</span><b>$70mm</b><small>Senior notes · 5%</small></div><div><span>CLASS B</span><b>$20mm</b><small>Mezz notes · 7%</small></div><div><span>RESIDUAL</span><b>$10mm</b><small>First-loss position</small></div></div><div className="math-card"><span>Monthly asset interest</span><b>$666,667</b><i>−</i><span>Fees + note interest</span><b>$501,667</b><i>=</i><span>Rough excess spread</span><b className="positive">$165,000</b></div><div className="challenge"><b>Your check</b><p>OC amount = $100mm collateral − $90mm rated notes = <strong>$10mm</strong>. OC ratio = $100mm ÷ $90mm = <strong>1.111x</strong>.</p></div></section>}
function InfoCard({icon,title,text}:{icon:string,title:string,text:string}){return <div className="info-card"><span>{icon}</span><b>{title}</b><p>{text}</p></div>}

function DemoLesson({day,section}:{day:number,section:number}){const lesson=demoDays[day];const item=lesson.sections[section];return <section className="deep-section demo-section"><span className="section-label">DAY {day} · {item.label.toUpperCase()}</span><p className="comic-kicker">{item.kicker}</p><h1>{item.title}</h1><p className="lead">{item.lead}</p><div className="demo-context"><div><span>BUILDS ON</span><b>{lesson.prerequisite}</b></div><i>→</i><div><span>TODAY</span><b>{lesson.shortTitle}</b></div><i>→</i><div><span>UNLOCKS</span><b>{lesson.later}</b></div></div><div className="demo-points">{item.bullets.map((bullet,i)=><article key={bullet.title}><span>{i+1}</span><div><b>{bullet.title}</b><p>{bullet.text}</p></div></article>)}</div><div className="plain-english"><b>💬 Remember this</b><p>{item.callout}</p></div></section>}

function MapTool({day,selected,setSelected,openFullMap}:{day:number,selected:number,setSelected:(n:number)=>void,openFullMap:()=>void}){const connections=day===1?mapNodes:[{day:Math.max(1,day-1),name:'Prerequisite',detail:demoDays[day].prerequisite,state:'next'},{day,name:demoDays[day].shortTitle,detail:`Current lesson: ${demoDays[day].title}`,state:'current'},{day:day===4?6:day+1,name:'Unlocks next',detail:demoDays[day].later,state:'milestone'}];const safe=Math.min(selected,connections.length-1);return <div className="interactive-tool"><div className="tool-head"><span>DAY {day} CONNECTIONS</span><b>{day===1?'You are at the foundation':'See what this lesson builds on'}</b></div><div className="vertical-map">{connections.map((node:any,i)=><button key={`${node.day}-${i}`} onClick={()=>setSelected(i)} className={`${node.state} ${safe===i?'selected':''}`}><span>{node.day}</span><p><b>{node.name}</b><small>{node.state==='current'?'NOW':node.state==='milestone'?'LATER':'BEFORE'}</small></p></button>)}</div><div className="map-detail"><span>DAY {connections[safe].day}</span><b>{connections[safe].name}</b><p>{connections[safe].detail}</p></div><button className="open-full-map" onClick={openFullMap}>Open full Learning Map <span>↗</span></button></div>}
function CardTool({data,index,setIndex,flipped,setFlipped,mastered,setMastered}:{data:{front:string;back:string}[],index:number,setIndex:(n:number)=>void,flipped:boolean,setFlipped:(b:boolean)=>void,mastered:number[],setMastered:(n:number[])=>void}){const safe=index%data.length;const card=data[safe];const known=mastered.includes(safe);function move(delta:number){setIndex((safe+delta+data.length)%data.length);setFlipped(false)}return <div className="interactive-tool"><div className="tool-head"><span>FLASHCARDS · {safe+1}/{data.length}</span><b>{mastered.length} mastered</b></div><button className={`flashcard ${flipped?'flipped':''}`} onClick={()=>setFlipped(!flipped)}><small>{flipped?'ANSWER':'TAP TO FLIP'}</small><strong>{flipped?card.back:card.front}</strong></button><div className="card-actions"><button onClick={()=>move(-1)} aria-label="Previous card">←</button><button className={known?'known':''} onClick={()=>setMastered(known?mastered.filter(n=>n!==safe):[...mastered,safe])}>{known?'✓ Mastered':'Mark mastered'}</button><button onClick={()=>move(1)} aria-label="Next card">→</button></div></div>}
function QuizTool({data,answers,setAnswers,submitted,setSubmitted,score}:{data:typeof quiz,answers:Record<number,number>,setAnswers:(a:Record<number,number>)=>void,submitted:boolean,setSubmitted:(b:boolean)=>void,score:number}){const next=Object.keys(answers).length;return <div className="interactive-tool quiz-tool"><div className="tool-head"><span>QUICK QUIZ</span><b>{submitted?`${score}/${data.length} correct`:`${next}/${data.length} answered`}</b></div>{data.map((item,i)=><div className="question" key={item.q}><p><b>{i+1}.</b> {item.q}</p><div>{item.options.map((option,j)=><button disabled={submitted} onClick={()=>setAnswers({...answers,[i]:j})} className={`${answers[i]===j?'chosen':''} ${submitted&&j===item.answer?'correct':''} ${submitted&&answers[i]===j&&j!==item.answer?'wrong':''}`} key={option}>{option}</button>)}</div>{submitted&&<small>{item.explain}</small>}</div>)}{!submitted?<button className="submit-quiz" disabled={Object.keys(answers).length<data.length} onClick={()=>setSubmitted(true)}>Submit answers</button>:<div className="result-box"><strong>{score/data.length>=.8?'🏆 Level cleared!':'↺ Good first run'}</strong><p>{score/data.length>=.8?'You reached the 80% mastery target.':'Review the explanations, then try again.'}</p>{score<data.length&&<button onClick={()=>{setAnswers({});setSubmitted(false)}}>Retry quiz</button>}</div>}</div>}

function GuidedTour({step,setStep}:{step:number,setStep:(n:number)=>void}){const [rect,setRect]=useState<{top:number,left:number,width:number,height:number}|null>(null);const item=tourSteps[step];useEffect(()=>{let timer:number;function locate(){const el=document.querySelector(item.target) as HTMLElement|null;if(!el){setRect(null);return;}el.scrollIntoView({behavior:'smooth',block:'center',inline:'center'});timer=window.setTimeout(()=>{const r=el.getBoundingClientRect();setRect({top:r.top-7,left:r.left-7,width:r.width+14,height:r.height+14});},250)}locate();window.addEventListener('resize',locate);return()=>{window.clearTimeout(timer);window.removeEventListener('resize',locate)}},[step,item.target]);const tooltipTop=rect?Math.min(window.innerHeight-250,Math.max(18,rect.top+rect.height+14)):window.innerHeight/2-110;const tooltipLeft=rect?Math.min(window.innerWidth-365,Math.max(18,rect.left)):window.innerWidth/2-175;return <div className="tour-layer" role="dialog" aria-modal="true" aria-label="Product tour"><div className="tour-scrim"/><div className="tour-highlight" style={rect||{top:'50%',left:'50%',width:0,height:0}}/><section className="tour-tip" style={{top:tooltipTop,left:tooltipLeft}}><div className="tour-step"><span>{item.eyebrow}</span><small>{step+1} / {tourSteps.length}</small></div><h2>{item.title}</h2><p>{item.text}</p><div><button className="tour-skip" onClick={()=>setStep(-1)}>Skip tour</button>{step>0&&<button onClick={()=>setStep(step-1)}>Back</button>}<button className="tour-next" onClick={()=>setStep(step===tourSteps.length-1?-1:step+1)}>{step===tourSteps.length-1?'Start Day 1':'Next'} →</button></div></section></div>}

function TopicLibrary({close}:{close:()=>void}){return <div className="topic-library-layer" role="dialog" aria-modal="true" aria-label="Study Arcade topic library"><button className="topic-backdrop" onClick={close} aria-label="Close topic library"/><section className="topic-library"><header><div><span className="eyebrow">STUDY ARCADE</span><h2>Topic Library</h2><p>Choose an organizational topic and enter its connected learning journey.</p></div><button onClick={close}>Close ×</button></header><div className="topic-library-intro"><strong>The platform stays familiar. The subject changes.</strong><p>Each topic can have its own syllabus, duration, learning map, presentations, practice, assessments, and mastery criteria.</p></div><div className="topic-grid"><button className="topic-card active-topic" onClick={close}><span className="topic-icon">SF</span><small>AVAILABLE NOW · 32 LEVELS</small><h3>Securitization Fundamentals</h3><p>Follow loans into bonds through structure, credit, cash flows, analysis, and applied deal thinking.</p><b>Continue topic →</b></button><article className="topic-card upcoming"><span className="topic-icon">PM</span><small>EXAMPLE FUTURE TOPIC</small><h3>Product Management Foundations</h3><p>A future organizational journey using the same Study Arcade learning system.</p><b>Coming soon</b></article><article className="topic-card upcoming"><span className="topic-icon">AI</span><small>EXAMPLE FUTURE TOPIC</small><h3>Responsible AI at Work</h3><p>Another example of how teams could publish a governed learning journey.</p><b>Coming soon</b></article></div><footer><span>＋</span><p><b>Built for many organizational topics</b>Your team can eventually add a governed syllabus without rebuilding the learning experience.</p></footer></section></div>}

function Presentation({day,section,setSection,close}:{day:number,section:number,setSection:(n:number)=>void,close:()=>void}){const isFirst=day===1;const count=isFirst?lessonSections.length:demoDays[day].sections.length;const title=isFirst?lessonSections[section].title:demoDays[day].sections[section].title;const label=isFirst?lessonSections[section].label:demoDays[day].sections[section].label;const summary=isFirst?[null,'Recycle capital · Lower funding cost · Transfer risk · Match cash flows','Originator · SPV · Servicer · Trustee · Investors · Rating agencies','Subordination · Overcollateralization · Excess spread · Reserve account','$100mm collateral → $90mm rated notes → $10mm first-loss cushion'][section]:demoDays[day].sections[section].bullets.map(b=>b.title).join(' · ');return <div className="presentation" role="dialog" aria-modal="true"><header><div className="brand-mark">SA</div><b>SECURITIZATION FUNDAMENTALS · DAY {day} · {label}</b><button onClick={close}>Exit presentation ×</button></header><main><span>STUDY ARCADE</span><h1>{title}</h1>{day===1&&section===0?<div className="presentation-flow"><b>🚗 Borrowers</b><i>→</i><b>🏦 Originator</b><i>→</i><b>📦 SPV</b><i>→</i><b>📊 Investors</b></div>:<p>{summary}</p>}</main><footer><button disabled={section===0} onClick={()=>setSection(section-1)}>← Previous</button><span>{section+1} / {count}</span><button disabled={section===count-1} onClick={()=>setSection(section+1)}>Next →</button></footer></div>}

function LearningMap({close,chooseDay}:{close:()=>void,chooseDay:(day:number)=>void}){return <div className="learning-map-modal" role="dialog" aria-modal="true" aria-label="Course learning map"><header><div><span className="eyebrow">YOUR COURSE INDEX + MENTAL MODEL</span><h2>Learning Map</h2><p>Follow the main path, then use the dotted connections to see which earlier ideas unlock later concepts.</p></div><button onClick={close}>Close ×</button></header><div className="map-legend"><span><i className="legend-current"/> Current</span><span><i className="legend-phase"/> Learning phase</span><span><i className="legend-link"/> Prerequisite connection</span></div><div className="phase-map">{phases.map((phase,index)=><section className={`phase-lane ${phase.tone}`} key={phase.name}><div className="phase-identity"><span>{index<5?`PHASE ${index+1}`:'BONUS'}</span><b>{phase.name}</b><small>Days {phase.days}</small></div><div className="phase-concepts"><p>{phase.concepts}</p><div className="phase-nodes">{phase.days.split('–').length===2?Array.from({length:Number(phase.days.split('–')[1])-Number(phase.days.split('–')[0])+1},(_,i)=>Number(phase.days.split('–')[0])+i).map(day=><button className={day===1?'current':''} onClick={()=>chooseDay(day)} key={day}><span>{day}</span><small>{levelTitles[day-1]}</small></button>):null}</div></div>{index<phases.length-1&&<i className="phase-arrow">↓</i>}</section>)}</div><div className="prerequisite-links"><span>KEY PREREQUISITE LINKS</span><div><p><b>Day 3 Tranches</b> unlocks <strong>Day 14 Advanced Waterfalls</strong></p><p><b>Day 4 Triggers</b> is tested in <strong>Day 12 Scenarios</strong></p><p><b>Day 5 Losses</b> is measured through <strong>Day 16 Vintage Analysis</strong></p><p><b>Day 7 Presales</b> becomes <strong>Day 18 Investor Memo</strong></p><p><b>Day 17 Data Tape</b> feeds <strong>Day 29 Excel Model</strong></p><p><b>Day 27 CE Backsolve</b> is applied in <strong>Day 28 Structuring Lab</strong></p></div></div></div>}
